### PR TITLE
fix:Make redisdown work with v6.x abstract-down

### PR DESCRIPTION
**Pull request by seigel**
When trying to get redisdown to work with pouchdb noticed that there were some issues with AbstractIterator and some other tests in #31 .  

This is a PR that allows redisdown to work with the test suite from  abstract-leveldown for v 6 along with some small clean up work.

### CODE REVIEW

**Comment by seigel** [comment]
Corrected some of the code for the other tests to pass from pouchdb suite.  Next will be to fix / add functionality for the excluded tests

**Comment by hmalphettes** [comment]
@seigel sorry for lagging your PR. I confess I am not using this library at the moment.

I have merged your previous PR.
This PR does not rely on the refactoring of `_end` to `_internalEnd`. This is where it conflicts at the moment.

Can you help resolve the conflict please?

On a separate note: I invited you to collaborate on this repo.
If you think we should transfer this repo somewhere else, l am opened to suggestions!

Thanks!

**Comment by seigel** [comment]
Thank you.  I will fix the conflicts.  I have no preference to move it at this time.  I don't use it a ton, but it is nice to have a clean install :D   I hope you are doing well and staying safe.

**Comment by seigel** [comment]
Hrmmm...I think that that github resolution led me down a weird path.  I *may* have updated master by accident :(  Next time, I'll use my own tools!

**Comment by antonkatz** [comment]
Can this get merged please? Thank you.

**Comment by seigel** [comment]
Yes.  I will do that.  I am not sure why that hadn't happened yet.  Sorry for the delay.

**Comment by antonkatz** [comment]
Thank you for your hard work! PS. There's also this issue, I'm not sure if it's applicable to this repo or just the fork. https://github.com/seigel/redisdown/pull/1

You're awesome

**Comment by seigel** [comment]
I will take a look and see if it is still applicable.

**Pull request merged**
